/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParticipantDialog.java
 *
 * Created on May 5, 2011, 2:27:19 PM
 */
package PYCA.gui;

import PYCA.model.District;
import PYCA.model.IDColor;
import PYCA.model.Participant;
import PYCA.model.Team;
import PYCA.model.Type;
import PYCA.model.Year;
import PYCA.services.implementation.DistrictServiceImpl;
import PYCA.services.implementation.IDColorServiceImpl;
import PYCA.services.implementation.ParticipantServiceImpl;
import PYCA.services.implementation.TeamServiceImpl;
import PYCA.services.implementation.TypeServiceImpl;
import PYCA.services.interfaces.DistrictService;
import PYCA.services.interfaces.IDColorService;
import PYCA.services.interfaces.ParticipantService;
import PYCA.services.interfaces.TeamService;
import PYCA.services.interfaces.TypeService;
import PYCA.tools.ExceptionHandler;
import PYCA.tools.FormValidation;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author YANIX-MRML
 */
public class ParticipantDialog extends javax.swing.JDialog {

    private Participant participant;
    private Year currentYear;
    private ParticipantService participantService;
    private TeamService teamService;
    private DistrictService districtService;
    private TypeService typeService;
    private IDColorService colorService;
    private String title;
    private ArrayList<Type> typeList;
    private ArrayList<Team> teamList;
    private ArrayList<District> districtList;
    private ArrayList<IDColor> colorList;
    private boolean isAdd;
    
    
    /** Creates new form ParticipantDialog */
    public ParticipantDialog(java.awt.Frame parent, boolean modal, Participant participant,Year currentYear) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        isAdd = true;
        this.participant = participant;
        this.currentYear = currentYear;
        title = "Add Participant";
        participantService = new ParticipantServiceImpl();
        teamService = new TeamServiceImpl();
        typeService = new TypeServiceImpl();
        districtService = new DistrictServiceImpl();
        colorService = new IDColorServiceImpl();
        setComboBoxes();
        displayParticipantInformation();
        this.setTitle(title);
    }
    
    private void setComboBoxes(){
        try {
            typeList = (ArrayList<Type>) typeService.getTypes();
            teamList = (ArrayList<Team>) teamService.getTeams(currentYear);
            districtList = (ArrayList<District>) districtService.getDistricts();
            colorList = (ArrayList<IDColor>) colorService.getIDColors(currentYear);
            
            for(Type type : typeList){
                typeCombo.addItem(type.getTypeName());
            }
            for(Team team : teamList){
                teamCombo.addItem(team.getTeamName());
            }
            for(District district : districtList){
                districtCombo.addItem(district.getDistrictName());
            }
            for(IDColor color : colorList){
                colorCombo.addItem(color.getColorName());
            }
        } catch (ExceptionHandler ex) {
            Logger.getLogger(ParticipantDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        firstNameTF = new javax.swing.JTextField();
        ageSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        middleNameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        nickNameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        districtCombo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        teamCombo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        colorCombo = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        rfCheck = new javax.swing.JCheckBox();
        pcCheck = new javax.swing.JCheckBox();
        gkkTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Participant");
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 3, true));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Panel.background"), 3, true));

        firstNameTF.setFont(new java.awt.Font("Calibri", 1, 14));

        ageSpinner.setFont(new java.awt.Font("Calibri", 1, 14));
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 10, 35, 1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel3.setText("Middle Name/Inital");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel8.setText("Type");

        typeCombo.setFont(new java.awt.Font("Calibri", 1, 14));
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>" }));
        typeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel4.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel6.setText("Age");

        middleNameTF.setFont(new java.awt.Font("Calibri", 1, 14));

        lastNameTF.setFont(new java.awt.Font("Calibri", 1, 14));

        nickNameTF.setFont(new java.awt.Font("Calibri", 1, 14));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel7.setText("Nickname");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel9.setText("District");

        districtCombo.setFont(new java.awt.Font("Calibri", 1, 14));
        districtCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>" }));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel10.setText("Team");

        teamCombo.setFont(new java.awt.Font("Calibri", 1, 14));
        teamCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>" }));
        teamCombo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel11.setText("ID Color");

        colorCombo.setFont(new java.awt.Font("Calibri", 1, 14));
        colorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Choose>" }));
        colorCombo.setEnabled(false);

        rfCheck.setFont(new java.awt.Font("Calibri", 1, 14));
        rfCheck.setText("Has Registration Fee");
        rfCheck.setOpaque(false);

        pcCheck.setFont(new java.awt.Font("Calibri", 1, 14));
        pcCheck.setText("Has Parental Consent");
        pcCheck.setOpaque(false);

        gkkTF.setFont(new java.awt.Font("Calibri", 1, 14));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14));
        jLabel12.setText("GKK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colorCombo, 0, 247, Short.MAX_VALUE)
                                    .addComponent(teamCombo, 0, 247, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rfCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(pcCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(95, 95, 95)
                                .addComponent(typeCombo, 0, 251, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(81, 81, 81)
                                .addComponent(districtCombo, 0, 251, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(middleNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(lastNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(nickNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(54, 54, 54)
                        .addComponent(ageSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(gkkTF, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middleNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gkkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfCheck)
                    .addComponent(pcCheck))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PYCA/resources/83.png"))); // NOI18N
        jLabel5.setText("Add Participant");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PYCA/resources/50.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PYCA/resources/15.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        participant = null;
        this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Participant newParticipant = null;
        
        if(!FormValidation.validateFirstName(firstNameTF.getText())){
            JOptionPane.showMessageDialog(this, "Invalid First Name",title,JOptionPane.WARNING_MESSAGE);
        }else if(!FormValidation.validateMiddleName(middleNameTF.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Middle Name",title,JOptionPane.WARNING_MESSAGE);
        }else if(!FormValidation.validateLastName(lastNameTF.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Last Name",title,JOptionPane.WARNING_MESSAGE);
        }else if(!FormValidation.validateFirstName(firstNameTF.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Nickname",title,JOptionPane.WARNING_MESSAGE);
        }else if(typeCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Choose Type",title,JOptionPane.WARNING_MESSAGE);
        }else if(districtCombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Choose District",title,JOptionPane.WARNING_MESSAGE);
        }else if(teamCombo.getSelectedIndex()==0 && !isAdd && typeCombo.getSelectedItem().toString().equalsIgnoreCase("Participant")){
            JOptionPane.showMessageDialog(this, "Choose Team",title,JOptionPane.WARNING_MESSAGE);
        }else if(colorCombo.getSelectedIndex()==0 && !isAdd && typeCombo.getSelectedItem().toString().equalsIgnoreCase("Participant")){
            JOptionPane.showMessageDialog(this, "Choose ID Color",title,JOptionPane.WARNING_MESSAGE);
        }else{
            
            newParticipant = new Participant();
            if(participant!=null){
                newParticipant.setParticipantID(participant.getParticipantID());
                newParticipant.setColor(participant.getColor());
                newParticipant.setTeam(participant.getTeam());
                newParticipant.setYear(participant.getYear());
            }else{
                newParticipant.setYear(currentYear);                 
                if(!typeCombo.getSelectedItem().toString().equalsIgnoreCase("Participant")){
                    newParticipant.setColor(null);
                    newParticipant.setTeam(null);
                }
            }
            newParticipant.setLastName(lastNameTF.getText());
            newParticipant.setMiddleName(middleNameTF.getText());
            newParticipant.setFirstName(firstNameTF.getText());
            newParticipant.setNickName(nickNameTF.getText());
            newParticipant.setType(typeList.get(typeCombo.getSelectedIndex()-1));
            newParticipant.setDistrict(districtList.get(districtCombo.getSelectedIndex()-1));
            newParticipant.setAge(Integer.parseInt(ageSpinner.getValue().toString()));
            if(gkkTF.getText().isEmpty()){
                newParticipant.setGkk(null);
            }else{
                newParticipant.setGkk(gkkTF.getText());
            }
            
            newParticipant.setRegistrationFee(rfCheck.isSelected());
            newParticipant.setParentalConsent(pcCheck.isSelected());
            saveParticipant(newParticipant);
            
        }
        
        
}//GEN-LAST:event_jButton1ActionPerformed

    private void typeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboItemStateChanged
        // TODO add your handling code here:
        if(typeCombo.getSelectedItem().toString().equalsIgnoreCase("Participant") && !isAdd){
            teamCombo.setEnabled(true);
            colorCombo.setEnabled(true);
        }else{
            teamCombo.setEnabled(false);
            colorCombo.setEnabled(false);
        }
    }//GEN-LAST:event_typeComboItemStateChanged

    private void saveParticipant(Participant newParticipant){
        
        if(isAdd){
                
            try {
                newParticipant = participantService.addParticipant(newParticipant);
                this.participant = newParticipant;
                this.setVisible(false);               
            } catch (ExceptionHandler ex) {
                Logger.getLogger(ParticipantDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{  
            
            try {
                participantService.editParticipant(newParticipant);
                participant = newParticipant;
                JOptionPane.showMessageDialog(this,"You have successfull added a participant", "Add Participant",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            } catch (ExceptionHandler ex) {
                Logger.getLogger(ParticipantDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }
    
    private void displayParticipantInformation(){
        if(participant!=null){
            lastNameTF.setText(participant.getLastName());
            firstNameTF.setText( participant.getFirstName());
            middleNameTF.setText(participant.getLastName());
            nickNameTF.setText(participant.getNickName());
            ageSpinner.setValue(participant.getAge());
            typeCombo.setSelectedItem(participant.getType().getTypeName());
            districtCombo.setSelectedItem(participant.getDistrict().getDistrictName());
            gkkTF.setText(participant.getGkk());
            rfCheck.setSelected(participant.isRegistrationFee());
            pcCheck.setSelected(participant.isParentalConsent());
            if(participant.getTeam()!=null){
                teamCombo.setSelectedItem(participant.getTeam().getTeamName());
            }
            if(participant.getColor()!=null){
                colorCombo.setSelectedItem(participant.getColor().getColorName());
            }
            title = "Edit Participant";
            if(participant.getType()!=null && participant.getType().getTypeName()!= null
                    && participant.getType().getTypeName().equalsIgnoreCase("Participant")){
                teamCombo.setEnabled(true);
                colorCombo.setEnabled(true);
            }
            isAdd = false;
        }
    }
    
    public Participant getParticipant(){
        return participant;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JComboBox colorCombo;
    private javax.swing.JComboBox districtCombo;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JTextField gkkTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JTextField middleNameTF;
    private javax.swing.JTextField nickNameTF;
    private javax.swing.JCheckBox pcCheck;
    private javax.swing.JCheckBox rfCheck;
    private javax.swing.JComboBox teamCombo;
    private javax.swing.JComboBox typeCombo;
    // End of variables declaration//GEN-END:variables
}
